import { Noticia } from '@/types';

export const mockNoticias: Noticia[] = [
  {
    id: '1',
    titulo: 'Central Goya inicia la pretemporada con grandes expectativas',
    resumen: 'El equipo de Primera División comenzó los entrenamientos con miras al nuevo torneo.',
    contenido: 'El Club Atlético Central Goya inició oficialmente la pretemporada con una convocatoria masiva de jugadores. El cuerpo técnico, liderado por el entrenador principal, ha diseñado un plan de trabajo intensivo que incluye preparación física, táctica y trabajo en grupo.',
    imagen: '/486688915_2636109269922248_5474496885224647034_n.jpg',
    categoria: 'Primera',
    fecha: '2024-01-15',
    autor: 'Prensa Central Goya',
    destacada: true,
    tags: ['Primera', 'Pretemporada', 'Entrenamientos'],
  },
  {
    id: '2',
    titulo: 'Las chicas del Fútbol Femenino se preparan para el campeonato',
    resumen: 'El equipo femenino de Central Goya comienza su preparación para la nueva temporada.',
    contenido: 'Con gran entusiasmo, el plantel femenino de Central Goya inició los entrenamientos. Las jugadoras mostraron un excelente nivel físico y técnico, demostrando el compromiso con el club.',
    imagen: '/450604841_2420050368194807_476765102751728094_n.jpg',
    categoria: 'Femenino',
    fecha: '2024-01-14',
    autor: 'Prensa Central Goya',
    destacada: true,
    tags: ['Femenino', 'Torneo', 'Preparación'],
  },
  {
    id: '3',
    titulo: 'Avances en las obras del nuevo vestuario',
    resumen: 'Continúan los trabajos de construcción del nuevo vestuario con un 60% de avance.',
    contenido: 'Las obras del nuevo vestuario avanzan según lo planificado. Se espera que esté terminado para el inicio del próximo torneo, mejorando significativamente las instalaciones del club.',
    imagen: '/466007273_10228817423593917_1038615226782194342_n.jpg',
    categoria: 'Obras',
    fecha: '2024-01-13',
    autor: 'Comisión Directiva',
    destacada: false,
    tags: ['Obras', 'Infraestructura', 'Mejoras'],
  },
  {
    id: '4',
    titulo: 'Los Pibes del Sur: La barra más fiel del club',
    resumen: 'Un reconocimiento especial a la hinchada que siempre está presente.',
    contenido: 'La barra "Los Pibes del Sur" ha demostrado una vez más su compromiso inquebrantable con el club, acompañando en cada partido tanto de local como de visitante.',
    imagen: '/517106609_10163747557199734_7756948239092276675_n.jpg',
    categoria: 'General',
    fecha: '2024-01-12',
    autor: 'Prensa Central Goya',
    destacada: false,
    tags: ['Barra', 'Hinchada', 'Pasión'],
  },
];
