import { Partido } from '@/types';

export const mockPartidos: Partido[] = [
  {
    id: '1',
    categoria: 'masculino',
    fecha: '2024-02-10',
    hora: '17:00',
    local: 'Central Goya',
    visitante: 'Deportivo Goya',
    estado: 'programado',
    cancha: 'Estadio Central Goya',
    torneo: 'Torneo Regional 2024',
    jornada: 1,
  },
  {
    id: '2',
    categoria: 'masculino',
    fecha: '2024-02-17',
    hora: '17:00',
    local: 'Sportivo Goya',
    visitante: 'Central Goya',
    estado: 'programado',
    cancha: 'Estadio Sportivo',
    torneo: 'Torneo Regional 2024',
    jornada: 2,
  },
  {
    id: '3',
    categoria: 'femenino',
    fecha: '2024-02-11',
    hora: '16:00',
    local: 'Central Goya',
    visitante: 'Atlético Goya',
    estado: 'programado',
    cancha: 'Estadio Central Goya',
    torneo: 'Liga Femenina 2024',
    jornada: 1,
  },
  {
    id: '4',
    categoria: 'juvenil',
    fecha: '2024-02-08',
    hora: '15:00',
    local: 'Central Goya',
    visitante: 'Juventud Goya',
    resultado: {
      golesLocal: 2,
      golesVisitante: 1,
    },
    estado: 'finalizado',
    cancha: 'Estadio Central Goya',
    torneo: 'Torneo Juvenil 2024',
    jornada: 3,
  },
  {
    id: '5',
    categoria: 'infantil',
    fecha: '2024-02-09',
    hora: '14:00',
    local: 'Central Goya',
    visitante: 'Escuela de Fútbol Goya',
    estado: 'programado',
    cancha: 'Cancha Auxiliar',
    torneo: 'Torneo Infantil 2024',
    jornada: 2,
  },
  {
    id: '6',
    categoria: 'veterano',
    fecha: '2024-02-15',
    hora: '18:00',
    local: 'Central Goya',
    visitante: 'Veteranos Unidos',
    estado: 'programado',
    cancha: 'Estadio Central Goya',
    torneo: 'Liga de Veteranos 2024',
    jornada: 1,
  },
];
