import { Producto } from '@/types';

export const mockProductos: Producto[] = [
  {
    id: '1',
    nombre: 'Camiseta Titular 2024',
    descripcion: 'Camiseta oficial del Club Atlético Central Goya temporada 2024. Incluye escudo bordado y sponsor.',
    precio: 15000,
    imagen: '/images/indumentaria/camiseta-titular.jpg',
    categoria: 'camiseta',
    talles: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: 50,
    destacado: true,
  },
  {
    id: '2',
    nombre: 'Camiseta Alternativa 2024',
    descripcion: 'Camiseta alternativa blanca con detalles en dorado y negro.',
    precio: 15000,
    imagen: '/images/indumentaria/camiseta-alternativa.jpg',
    categoria: 'camiseta',
    talles: ['S', 'M', 'L', 'XL'],
    stock: 30,
    destacado: false,
  },
  {
    id: '3',
    nombre: 'Short Oficial 2024',
    descripcion: 'Short oficial del club con detalles en dorado.',
    precio: 5000,
    imagen: '/images/indumentaria/short.jpg',
    categoria: 'short',
    talles: ['S', 'M', 'L', 'XL'],
    stock: 40,
    destacado: false,
  },
  {
    id: '4',
    nombre: 'Medias Oficiales',
    descripcion: 'Medias oficiales del club con rayas negras y blancas.',
    precio: 2500,
    imagen: '/images/indumentaria/medias.jpg',
    categoria: 'medias',
    talles: ['Único'],
    stock: 60,
    destacado: false,
  },
  {
    id: '5',
    nombre: 'Bufanda Oficial',
    descripcion: 'Bufanda oficial del club con los colores institucionales.',
    precio: 3500,
    imagen: '/images/indumentaria/bufanda.jpg',
    categoria: 'accesorios',
    talles: ['Único'],
    stock: 25,
    destacado: true,
  },
  {
    id: '6',
    nombre: 'Gorra Oficial',
    descripcion: 'Gorra con el escudo del club bordado.',
    precio: 4000,
    imagen: '/images/indumentaria/gorra.jpg',
    categoria: 'accesorios',
    talles: ['Único'],
    stock: 20,
    destacado: false,
  },
];
