import { Torneo } from '@/types';

export const mockTorneos: Torneo[] = [
  {
    id: '1',
    nombre: 'Torneo Regional 2024',
    categoria: 'masculino',
    temporada: '2024',
    formato: 'Liga todos contra todos',
    equipos: 12,
    fechaInicio: '2024-02-01',
    fechaFin: '2024-12-15',
    estado: 'enCurso',
    tabla: {
      posicion: 1,
      equipo: 'Central Goya',
      puntos: 15,
      partidosJugados: 5,
      ganados: 5,
      empatados: 0,
      perdidos: 0,
      golesFavor: 12,
      golesContra: 3,
      diferenciaGol: 9,
    },
  },
  {
    id: '2',
    nombre: 'Liga Femenina 2024',
    categoria: 'femenino',
    temporada: '2024',
    formato: 'Liga todos contra todos',
    equipos: 8,
    fechaInicio: '2024-02-01',
    fechaFin: '2024-11-30',
    estado: 'enCurso',
  },
  {
    id: '3',
    nombre: 'Torneo Juvenil 2024',
    categoria: 'juvenil',
    temporada: '2024',
    formato: 'Liga todos contra todos',
    equipos: 10,
    fechaInicio: '2024-01-15',
    fechaFin: '2024-10-31',
    estado: 'enCurso',
  },
  {
    id: '4',
    nombre: 'Torneo Infantil 2024',
    categoria: 'infantil',
    temporada: '2024',
    formato: 'Liga todos contra todos',
    equipos: 6,
    fechaInicio: '2024-02-01',
    fechaFin: '2024-11-30',
    estado: 'enCurso',
  },
  {
    id: '5',
    nombre: 'Liga de Veteranos 2024',
    categoria: 'veterano',
    temporada: '2024',
    formato: 'Liga todos contra todos',
    equipos: 8,
    fechaInicio: '2024-02-01',
    fechaFin: '2024-11-30',
    estado: 'inscripcion',
  },
];
